---
- name: Install Pip and pip3
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-pip
    - python3-pip

- name: Upgrade Pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3.5
